In [10]:
import numpy as np
import pandas as pd

In [11]:
df=pd.read_csv(r"D:\SEM-5\ML-LAB\ex-1\new_forest_full_dataset.csv")
df

day  month  year          Region  Temperature   RH   Ws  Rain   FFMC   
0      1      6  2012          Bejaia           29   57   18    0.0  65.7  \
1      2      6  2012          Bejaia           29   61   13    1.3  64.4   
2      3      6  2012          Bejaia           26   82   22   13.1  47.1   
3      4      6  2012          Bejaia           25   89   13    2.5  28.6   
4      5      6  2012          Bejaia           27   77   16    0.0  64.8   
..   ...    ...   ...             ...          ...  ...  ...    ...   ...   
239   26      9  2012  Sidi-Bel-Abbes           30   65   14    0.0  85.4   
240   27      9  2012  Sidi-Bel-Abbes           28   87   15    4.4  41.1   
241   28      9  2012  Sidi-Bel-Abbes           27   87   29    0.5  45.9   
242   29      9  2012  Sidi-Bel-Abbes           24   54   18    0.1  79.7   
243   30      9  2012  Sidi-Bel-Abbes           24   64   15    0.2  67.3   

      DMC    DC  ISI   BUI  FWI Classes    
0     3.4   7.6  1.3   3.4  0.5     no     
1     4.1   7.6  1.0   3.9  0.4     no     
2     2.5   7.1  0.3   2.7  0.1     no     
3     1.3   6.9  0.0   1.7  0.0     no     
4     3.0  14.2  1.2   3.9  0.5     no     
..    ...   ...  ...   ...  ...       ...  
239  16.0  44.5  4.5  16.9  6.5    yes     
240   6.5   8.0  0.1   6.2  0.0     no     
241   3.5   7.9  0.4   3.4  0.2     no     
242   4.3  15.2  1.7   5.1  0.7     no     
243   3.8  16.5  1.2   4.8  0.5    no      

[244 rows x 15 columns]

In [12]:
df.columns=df.columns.str.strip()
df['Classes']=df['Classes'].str.strip()
df['Classes'].value_counts()

Classes
yes    138
no     106
Name: count, dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Classes']=le.fit_transform(df['Classes'])
df

day  month  year          Region  Temperature  RH  Ws  Rain  FFMC   DMC   
0      1      6  2012          Bejaia           29  57  18   0.0  65.7   3.4  \
1      2      6  2012          Bejaia           29  61  13   1.3  64.4   4.1   
2      3      6  2012          Bejaia           26  82  22  13.1  47.1   2.5   
3      4      6  2012          Bejaia           25  89  13   2.5  28.6   1.3   
4      5      6  2012          Bejaia           27  77  16   0.0  64.8   3.0   
..   ...    ...   ...             ...          ...  ..  ..   ...   ...   ...   
239   26      9  2012  Sidi-Bel-Abbes           30  65  14   0.0  85.4  16.0   
240   27      9  2012  Sidi-Bel-Abbes           28  87  15   4.4  41.1   6.5   
241   28      9  2012  Sidi-Bel-Abbes           27  87  29   0.5  45.9   3.5   
242   29      9  2012  Sidi-Bel-Abbes           24  54  18   0.1  79.7   4.3   
243   30      9  2012  Sidi-Bel-Abbes           24  64  15   0.2  67.3   3.8   

       DC  ISI   BUI  FWI  Classes  
0     7.6  1.3   3.4  0.5        0  
1     7.6  1.0   3.9  0.4        0  
2     7.1  0.3   2.7  0.1        0  
3     6.9  0.0   1.7  0.0        0  
4    14.2  1.2   3.9  0.5        0  
..    ...  ...   ...  ...      ...  
239  44.5  4.5  16.9  6.5        1  
240   8.0  0.1   6.2  0.0        0  
241   7.9  0.4   3.4  0.2        0  
242  15.2  1.7   5.1  0.7        0  
243  16.5  1.2   4.8  0.5        0  

[244 rows x 15 columns]

In [14]:
df=df.drop('Region',axis=1)

day  month  year  Temperature  RH  Ws  Rain  FFMC   DMC    DC  ISI   BUI   
0      1      6  2012           29  57  18   0.0  65.7   3.4   7.6  1.3   3.4  \
1      2      6  2012           29  61  13   1.3  64.4   4.1   7.6  1.0   3.9   
2      3      6  2012           26  82  22  13.1  47.1   2.5   7.1  0.3   2.7   
3      4      6  2012           25  89  13   2.5  28.6   1.3   6.9  0.0   1.7   
4      5      6  2012           27  77  16   0.0  64.8   3.0  14.2  1.2   3.9   
..   ...    ...   ...          ...  ..  ..   ...   ...   ...   ...  ...   ...   
239   26      9  2012           30  65  14   0.0  85.4  16.0  44.5  4.5  16.9   
240   27      9  2012           28  87  15   4.4  41.1   6.5   8.0  0.1   6.2   
241   28      9  2012           27  87  29   0.5  45.9   3.5   7.9  0.4   3.4   
242   29      9  2012           24  54  18   0.1  79.7   4.3  15.2  1.7   5.1   
243   30      9  2012           24  64  15   0.2  67.3   3.8  16.5  1.2   4.8   

     FWI  Classes  
0    0.5        0  
1    0.4        0  
2    0.1        0  
3    0.0        0  
4    0.5        0  
..   ...      ...  
239  6.5        1  
240  0.0        0  
241  0.2        0  
242  0.7        0  
243  0.5        0  

[244 rows x 14 columns]

In [15]:
df=df.drop('year',axis=1)

In [16]:
df

day  month  Temperature  RH  Ws  Rain  FFMC   DMC    DC  ISI   BUI  FWI   
0      1      6           29  57  18   0.0  65.7   3.4   7.6  1.3   3.4  0.5  \
1      2      6           29  61  13   1.3  64.4   4.1   7.6  1.0   3.9  0.4   
2      3      6           26  82  22  13.1  47.1   2.5   7.1  0.3   2.7  0.1   
3      4      6           25  89  13   2.5  28.6   1.3   6.9  0.0   1.7  0.0   
4      5      6           27  77  16   0.0  64.8   3.0  14.2  1.2   3.9  0.5   
..   ...    ...          ...  ..  ..   ...   ...   ...   ...  ...   ...  ...   
239   26      9           30  65  14   0.0  85.4  16.0  44.5  4.5  16.9  6.5   
240   27      9           28  87  15   4.4  41.1   6.5   8.0  0.1   6.2  0.0   
241   28      9           27  87  29   0.5  45.9   3.5   7.9  0.4   3.4  0.2   
242   29      9           24  54  18   0.1  79.7   4.3  15.2  1.7   5.1  0.7   
243   30      9           24  64  15   0.2  67.3   3.8  16.5  1.2   4.8  0.5   

     Classes  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
239        1  
240        0  
241        0  
242        0  
243        0  

[244 rows x 13 columns]

In [17]:

def activation(net_inp,ch):
    if(ch==1):
        return net_inp
    elif(ch==2):
        return round(1/(1+np.exp(-net_inp)))
    elif(ch==3):
        return round((1-np.exp(-net_inp))/(1+np.exp(-net_inp)))

def predict(inputs,weights,bias,ch):
    inputs=np.dot(inputs,weights)+bias
    return activation(inputs,ch)

def feed_forward(data,target,weights,bias,lr,ch):
    converged=False
    epoch=0
    print("\len ",len(data))
    while not converged and epoch<=10:
        converged=True
        print("EPOCH : ",epoch)
        print("Weights : ",weights)
        print("Bias :",bias)
        print(data[0])
        for i in range(len(data)):
            pred=predict(data[i],weights,bias,ch)
            error=target[i]-pred
            #print("for data ",data[i],"PRED is ",pred)
            if error!=0:
             #  print("Updating Weights : ")
                weights+=lr*error*data[i]
                bias+=lr*error
              # print("New Weights : ",weights)
               #print("New Bias :",bias)
                converged=False
        epoch+=1
   # print('\nFinal weights:',weights)
    #print('Bias:',bias,"\n")
    return weights,bias

In [19]:
X=np.array(df.iloc[:,:-1])
y=np.array(df['Classes'])

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
X_train.shape


(195, 12)

In [21]:
weights=np.random.randn(len(df.columns[:-1]))
print(weights)
weights.shape

[ 0.67857701 -0.41673601 -2.35132921  1.44988076 -2.25807493 -1.25077753
  0.09647674 -1.01136999  0.12458759  0.8623122   1.11353525  1.3745716 ]


(12,)

In [22]:
bias=float(input("Enter the bias:"))
lr=float(input("Enter the learning rate:"))
ch=int(input("1.IDENTITY FXN\n2.BINARY SIGMOIDAL\n3.BIPOLAR SIGMOIDAL\nEnter the Choice of A.F : "))
if(ch==2 or ch==3):
    thresh=float(input('Enter the threshold:'))

weights,bias=feed_forward(X_train,y_train,weights,bias,lr,ch)
print("\nFinal Weights and Bias : ",weights,bias)

pred=[]
for test in X_test:
    p=predict(test,weights,bias,ch)
    pred.append(p)
    print("Input:",test,"Prediction:",p)
print(pred)


Enter the bias:0
Enter the learning rate:1
1.IDENTITY FXN
2.BINARY SIGMOIDAL
3.BIPOLAR SIGMOIDAL
Enter the Choice of A.F : 2
Enter the threshold:0.5
\len  195
EPOCH :  0
Weights :  [ 0.67857701 -0.41673601 -2.35132921  1.44988076 -2.25807493 -1.25077753
  0.09647674 -1.01136999  0.12458759  0.8623122   1.11353525  1.3745716 ]
Bias : 0.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]
EPOCH :  1
Weights :  [-150.32142299  -24.41673601  -80.35132921 -240.55011924  -34.25807493
  -12.55077753  104.89647674   59.98863001  171.02458759  111.5623122
   83.51353525  149.4745716 ]
Bias : -3.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]
EPOCH :  2
Weights :  [-215.32142299  -29.41673601  -85.35132921 -239.55011924  -68.25807493
  -28.45077753  215.99647674   82.38863001  152.42458759  164.1623122
  113.31353525  225.1745716 ]
Bias : -4.0
[26.   6.  31.  64.  18.   0.  86.8 17.8 71.8  6.7 21.6 10.6]
EPOCH :  3
Weights :  [-326.32142299  -44.41673601 -119.35132921 

C:\Users\MAAL SUBIKSHA\AppData\Local\Temp\ipykernel_11912\3062213435.py:5: RuntimeWarning: overflow encountered in exp
  return round(1/(1+np.exp(-net_inp)))


In [23]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,pred))

0.8979591836734694
